### ISSUE TITLE
[Bug]: Xorg crashes with error code 1

### ISSUE THREAD

**Issue by ameoverflow** [Steam-Headless/docker-steam-headless#200]
### Describe the Bug

Xorg doesn't run, causing the image to not work at all

### Steps to Reproduce

1. `docker compose up`

### Expected Behavior

Xorg should run

### Version

Build: [2025-09-27 02:47:51] [master] [23e5ec9fa4747ea05219b66ec938112c2a0fa110] [debian]

### Platform

 - Distribution: Arch Linux -
 - Linux Kernel: 6.16.8-arch3-1 unknown unknown GNU/Linux
 - GPU Driver: | NVIDIA-SMI 580.82.09 Driver Version: 580.82.09 CUDA Version: 13.0 |
 - Docker: Docker version 27.3.1, build ce1223035a
 - Docker compose: docker-compose 2.39.4-1

### Relevant log output

```Shell
steam-headless-1  | WARNING: Unable to locate/open X configuration file.
steam-headless-1  | 
steam-headless-1  | Option "ProbeAllGpus" "False" added to Screen "Screen0".
steam-headless-1  | Option "BaseMosaic" "False" added to Screen "Screen0".
steam-headless-1  | Option "AllowEmptyInitialConfiguration" "True" added to Screen "Screen0".
steam-headless-1  | New X configuration file written to '/etc/X11/xorg.conf'

steam-headless-1  | 2025-09-29 15:23:27,661 INFO Included extra file "/etc/supervisor.d/dbus.ini" during parsing
steam-headless-1  | 2025-09-29 15:23:27,661 INFO Included extra file "/etc/supervisor.d/desktop.ini" during parsing
steam-headless-1  | 2025-09-29 15:23:27,661 INFO Included extra file "/etc/supervisor.d/neko.ini" during parsing
steam-headless-1  | 2025-09-29 15:23:27,661 INFO Included extra file "/etc/supervisor.d/pulseaudio.ini" during parsing
steam-headless-1  | 2025-09-29 15:23:27,661 INFO Included extra file "/etc/supervisor.d/steam.ini" during parsing
steam-headless-1  | 2025-09-29 15:23:27,661 INFO Included extra file "/etc/supervisor.d/sunshine.ini" during parsing
steam-headless-1  | 2025-09-29 15:23:27,661 INFO Included extra file "/etc/supervisor.d/udev.ini" during parsing
steam-headless-1  | 2025-09-29 15:23:27,661 INFO Included extra file "/etc/supervisor.d/vnc-audio.ini" during parsing
steam-headless-1  | 2025-09-29 15:23:27,661 INFO Included extra file "/etc/supervisor.d/vnc.ini" during parsing
steam-headless-1  | 2025-09-29 15:23:27,661 INFO Included extra file "/etc/supervisor.d/wol-power-manager.ini" during parsing
steam-headless-1  | 2025-09-29 15:23:27,661 INFO Included extra file "/etc/supervisor.d/xorg.ini" during parsing
steam-headless-1  | 2025-09-29 15:23:27,661 INFO Included extra file "/etc/supervisor.d/xvfb.ini" during parsing
steam-headless-1  | 2025-09-29 15:23:27,661 INFO Set uid to user 0 succeeded
steam-headless-1  | 2025-09-29 15:23:27,663 INFO RPC interface 'supervisor' initialized
steam-headless-1  | 2025-09-29 15:23:27,663 CRIT Server 'unix_http_server' running without any HTTP authentication checking
steam-headless-1  | 2025-09-29 15:23:27,663 INFO supervisord started with pid 1
steam-headless-1  | 2025-09-29 15:23:28,665 INFO spawned: 'dbus' with pid 572
steam-headless-1  | 2025-09-29 15:23:28,667 INFO spawned: 'udev' with pid 573
steam-headless-1  | 2025-09-29 15:23:28,667 INFO spawned: 'xorg' with pid 574
steam-headless-1  | 2025-09-29 15:23:28,668 INFO spawned: 'pulseaudio' with pid 575
steam-headless-1  | 2025-09-29 15:23:28,669 INFO spawned: 'desktop' with pid 576
steam-headless-1  | 2025-09-29 15:23:28,670 INFO spawned: 'sunshine' with pid 578
steam-headless-1  | PULSEAUDIO: Starting pulseaudio service
steam-headless-1  | 2025-09-29 15:23:28,680 INFO reaped unknown pid 590 (exit status 0)
steam-headless-1  | 2025-09-29 15:23:29,675 INFO success: dbus entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2025-09-29 15:23:29,675 INFO success: udev entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2025-09-29 15:23:29,675 INFO success: xorg entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2025-09-29 15:23:29,675 INFO success: pulseaudio entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2025-09-29 15:23:29,675 INFO success: desktop entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2025-09-29 15:23:29,675 INFO success: sunshine entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2025-09-29 15:23:29,675 WARN exited: xorg (exit status 1; not expected)
steam-headless-1  | 2025-09-29 15:23:30,677 INFO spawned: 'xorg' with pid 619
steam-headless-1  | 2025-09-29 15:23:30,684 WARN exited: xorg (exit status 1; not expected)
steam-headless-1  | 2025-09-29 15:23:31,686 INFO spawned: 'xorg' with pid 631
steam-headless-1  | 2025-09-29 15:23:31,694 WARN exited: xorg (exit status 1; not expected)
steam-headless-1  | 2025-09-29 15:23:33,696 INFO spawned: 'xorg' with pid 651
steam-headless-1  | 2025-09-29 15:23:33,703 WARN exited: xorg (exit status 1; not expected)
steam-headless-1  | 2025-09-29 15:23:36,707 INFO spawned: 'xorg' with pid 679
steam-headless-1  | 2025-09-29 15:23:36,714 WARN exited: xorg (exit status 1; not expected)
steam-headless-1  | 2025-09-29 15:23:37,715 INFO gave up: xorg entered FATAL state, too many start retries too quickly
steam-headless-1  | 2025-09-29 15:23:58,798 WARN exited: desktop (exit status 11; not expected)
steam-headless-1  | 2025-09-29 15:23:58,799 INFO spawned: 'desktop' with pid 859
steam-headless-1  | 2025-09-29 15:23:58,815 WARN exited: sunshine (exit status 11; not expected)
steam-headless-1  | 2025-09-29 15:23:58,815 INFO reaped unknown pid 865 (exit status 0)
steam-headless-1  | 2025-09-29 15:23:58,816 INFO spawned: 'sunshine' with pid 870
steam-headless-1  | 2025-09-29 15:24:00,120 INFO success: desktop entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2025-09-29 15:24:00,120 INFO success: sunshine entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2025-09-29 15:24:28,925 WARN exited: desktop (exit status 11; not expected)
steam-headless-1  | 2025-09-29 15:24:28,926 INFO spawned: 'desktop' with pid 1114
steam-headless-1  | 2025-09-29 15:24:29,237 WARN exited: sunshine (exit status 11; not expected)
steam-headless-1  | 2025-09-29 15:24:29,237 INFO reaped unknown pid 1120 (exit status 0)
steam-headless-1  | 2025-09-29 15:24:29,238 INFO spawned: 'sunshine' with pid 1125
steam-headless-1  | 2025-09-29 15:24:30,263 INFO success: desktop entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2025-09-29 15:24:30,263 INFO success: sunshine entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

```
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing log file.
```

**Comment by zer0ish** [comment]
I have this same issue on a fresh install. 
Using portainer on truenas.

EDIT:
I seem to be able to get it working on my Unraid server but not on my truenas server.
Both can get to the VNC browser page, but only the Unraid one can connect to steamheadless and launch steam and play.

**Comment by gymnae** [comment]
~~~Facing the same issue on an existing installation. 
Fedora 42 LXC guest in a Proxmox 9 host. Not sure what happened, but now it won't run anymore.
Nvidia 580 series drivers, Kernel 6.14.11-3-pve

This could be helpful from the Xorg log:
```
[344367.861] (II) Loading /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so
[344367.869] (II) Module glxserver_nvidia: vendor="NVIDIA Corporation"
[344367.869] 	compiled for 1.6.99.901, module version = 1.0.0
[344367.869] 	Module class: X.Org Server Extension
[344367.869] (II) NVIDIA GLX Module  580.95.05  Tue Sep 23 09:49:15 UTC 2025
[344367.869] (II) NVIDIA: The X server supports PRIME Render Offload.
[344367.875] (--) NVIDIA(0): Valid display device(s) on GPU-0 at PCI:1:0:0
[344367.875] (--) NVIDIA(0):     DFP-0
[344367.875] (--) NVIDIA(0):     DFP-1
[344367.875] (--) NVIDIA(0):     DFP-2
[344367.875] (--) NVIDIA(0):     DFP-3
[344367.875] (--) NVIDIA(0):     DFP-4
[344367.875] (--) NVIDIA(0):     DFP-5
[344367.875] (--) NVIDIA(0):     DFP-6
[344367.878] (**) NVIDIA(0): Using ConnectedMonitor string "DFP-0".
[344367.878] (WW) NVIDIA: No path to DRM device: No direct render devices found.
[344367.894] (II) NVIDIA(0): NVIDIA GPU NVIDIA GeForce RTX 3060 (GA106-A) at PCI:1:0:0
[344367.894] (II) NVIDIA(0):     (GPU-0)
[344367.894] (--) NVIDIA(0): Memory: 12582912 kBytes
[344367.894] (--) NVIDIA(0): VideoBIOS: 94.06.14.40.2b
[344367.894] (II) NVIDIA(0): Detected PCI Express Link width: 16X
[344367.894] (EE) NVIDIA(GPU-0): Failed to acquire modesetting permission.
[344367.894] (EE) NVIDIA(0): Failing initialization of X screen
[344367.901] (II) UnloadModule: "nvidia"
[344367.901] (II) UnloadSubModule: "glxserver_nvidia"
[344367.901] (II) Unloading glxserver_nvidia
[344367.901] (II) UnloadSubModule: "wfb"
[344367.901] (EE) Screen(s) found, but none have a usable configuration.
[344367.901] (EE)
Fatal server error:
[344367.901] (EE) no screens found(EE)
[344367.901] (EE)~~~
```

Fixed it. In my case it was an issue that the mapping of the DRI devices switched and card0, which was the iGPU, is no the NVIDIA dGPU. So I needed to adjust the LXC config

**Comment by zer0ish** [comment]
It still works on fresh installs, but you can't use the docker compose template and env options provided. Not sure why that doesn't work.
Here is what worked for me, change the volumes and names as need. This is build from the unraid details and I made it into a compose format. 

With the bellow I was able to get everything working perfectly and gaming again.
Tested in both Portainer and Arcane, on my TrueNAS and Unraid server.
For this to work on TrueNAS I had to change the 8086 port on host side even thought I didn't have any containers using that port.


```
---
services:
  steam-headless_new:  # change the name to what you want
    image: josh5/steam-headless:latest
    restart: unless-stopped
    ## NOTE: This config uses privileged to access to host to be able to access the required devices
    privileged: true
    runtime: nvidia
    container_name: Steam-Headless_NEW  # change the name to what you want
    shm_size: 6G
    ipc: host # Could also be set to 'shareable'
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    extra_hosts:
      - "Steam-Headless_NEW:127.0.0.1" # change the name to match container/hostname
    
    # NETWORK:
    ## NOTE:  With this configuration, if we do not use the host network, then physical device input
    ##        is not possible and your USB connected controllers will not work in steam games.
#    network_mode: host
    hostname: Steam-Headless_NEW  # change the name to what you want

    ports:
      - 8086:8086
    
    # ENVIRONMENT:
    ## Read all config variables from the .env file
    environment:
      # System
      - TZ=America/Toronto
      - USER_LOCALES=en_US.UTF-8 UTF-8
      - DISPLAY=:55
      # User
      - PUID=99  # 99 for unraid / or what ever user for the OS you're using
      - PGID=100  # 100 for unraid / or what ever user for the OS you're using
#      - UMASK=
      - USER_PASSWORD=   #what ever password you want to use, not sure what it's used for
      # Mode
      - MODE=primary
      # Web UI
      - WEB_UI_MODE=vnc
      - ENABLE_VNC_AUDIO=false
      - PORT_NOVNC_WEB=8086
      # Nvidia specific config
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all   #or what ever GPU ID you want to use
      - NVIDIA_DRIVER_VERSION=  # I left this blank to use what was the base server drivers.

    # VOLUMES:
    volumes:
      - /CHANGE/TO/YOUR/PATH/:/home/default
      - /CHANGE/TO/YOUR/PATH/:/mnt/games
     
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /tmp/tmp/pulse/:/tmp/tmp/pulse/
      - /dev/input/:/dev/input/
```

**Comment by mblazic** [comment]
Can confirm, same issue here.
NVIDIA Driver: 580.95.05

**Comment by Jawzper** [comment]
Same error code on 7900xtx with mesa 25.2.6. 

Would appreciate if someone who resolved this already can clarify what caused the issue for them and how I can troubleshoot, I can't just copy nvidia config.

**Comment by ricardolee** [comment]
Can confirm, same issue here.

NVIDIA Driver: 580.105.08

**Comment by omigeot** [comment]
Same issue here, NVIDIA Driver: 580.95.05

**Comment by zer0ish** [comment]
Question:
Have any of you still having this issue attempted the solution I posted October 8th? I've had no issues with any new nvidia driver updates as-well.
I've had no issues playing with Steam Headless since I followed the steps I posted.

Use the template I provides for Docker compose, change the lines mentioned where needed.
Skip the env file and put everything in one docker compose as shown.

Maybe posting you docker compose config can help, because no new info is being provided by anyone.

All of you just posted the error with no info on what your compose file looks like. 

I'm enjoying the container just fine. So please try it, and if you still have issues, like all troubleshooting requests, post your configs, otherwise it's unlikely it will be resolved.

**Comment by ricardolee** [comment]
I found that Xorg is working correctly using the bridge network mode, but I did not see the same ports as the host.

**Comment by royinx** [comment]
I encountered the same issue, but in Ubuntu 20.04 , (Fresh installed OS, clean)
- CPU: Ryzen9 3950X (no iGPU)
- GPU: MSI RTX 4090
- OS:  Ubuntu 20.04.6 LTS
- Kernel: 5.15.0-139-generic
- Docker: Docker version 28.1.1, build 4eba377
- Host driver: 580.105.08

`docker-compose.yml` is the same **zer0ish** provided above, just changed the volume path for log & game folder.

## situation: 
Able to connect `http://<ip>:8086`, showing the VNC page , `Failed to connect to server` banner pops out when clicking `Connect` button. 

## attempted:
- [x] (host) blacklist noveau (`blacklist nouveau` & `options nouveau modeset=0`)
- [x] (host) setting drm (`options nvidia-drm modeset=1`)
- [x] tried `DISPLAY=:55`
- [x] (container)tried different nvidia driver  `580.105.08(cuda13.0)` & `570.124.04(cuda12.8)` 
- [x] (debugging) trying to forward X11 to host `DISPLAY=:0` , `DISPLAY=unix:0` , checking Xorg or gpu driver problem


## Log: 
```bash
[ /etc/cont-init.d/10-setup_user.sh: executing... ]
**** Configure default user ****
  - Setting default user uid=99(default) gid=100(default)
usermod: no changes
  - Adding default user to any additional required device groups
  - Adding user 'default' to group: 'video'
  - Adding user 'default' to group: 'audio'
  - Adding user 'default' to group: 'input'
  - Adding user 'default' to group: 'pulse'
  - Adding user 'default' to group: 'avahi' for device: /dev/input/event0
  - Setting umask to 000
  - Create the user XDG_RUNTIME_DIR path '/tmp/.X11-unix/run'
  - Setting ownership of all log files in '/home/default/.cache/log'
  - Setting root password
  - Setting user password
DONE

[ /etc/cont-init.d/11-setup_sysctl_values.sh: executing... ]
**** Configure some system kernel parameters ****
  - The vm.max_map_count is already greater than '524288'
DONE

[ /etc/cont-init.d/30-configure_dbus.sh: executing... ]
**** Configure container dbus ****
  - Container configured to run its own dbus
DONE

[ /etc/cont-init.d/30-configure_udev.sh: executing... ]
**** Configure udevd ****
  - Configure container to run udev management
  - Ensure the default user has permission to r/w on input devices
DONE

[ /etc/cont-init.d/40-setup_locale.sh: executing... ]
**** Configure local ****
  - Locales already set correctly to en_US.UTF-8 UTF-8
DONE

[ /etc/cont-init.d/50-configure_pulseaudio.sh: executing... ]
**** Configure pulseaudio ****
  - Enable pulseaudio service.
  - Configure pulseaudio to pipe audio to a socket
DONE

[ /etc/cont-init.d/60-configure_gpu_driver.sh: executing... ]
**** No Intel device found ****
**** No AMD device found ****
**** Found NVIDIA device 'NVIDIA GeForce RTX 4090' ****
  - NVIDIA driver version 580.105.08 is already installed
  - Leaving NVIDIA driver stock without patching
DONE

[ /etc/cont-init.d/70-configure_desktop.sh: executing... ]
**** Configure Desktop ****
  - Enable Desktop service.
DONE

[ /etc/cont-init.d/70-configure_xorg.sh: executing... ]
**** Generate NVIDIA xorg.conf ****
  - Configure container as primary the X server
  - Enabling evdev input class on pointers, keyboards, touchpads, touch screens, etc.
  - Configuring X11 with GPU ID: 'GPU-7e6f4521-b3fc-657c-0366-4c4c2a3c0299'
  - Configuring X11 with PCI bus ID: 'PCI:41:0:0'
  - Writing X11 config with Modeline "1600x900R"  201.00  1600 1648 1680 1760  900 903 908 953 +hsync -vsync

WARNING: Unable to locate/open X configuration file.

Option "ProbeAllGpus" "False" added to Screen "Screen0".
Option "BaseMosaic" "False" added to Screen "Screen0".
Option "AllowEmptyInitialConfiguration" "True" added to Screen "Screen0".
New X configuration file written to '/etc/X11/xorg.conf'

DONE

[ /etc/cont-init.d/80-configure_flatpak.sh: executing... ]
**** Configure Flatpak ****
  - Flatpak configured for running inside a Docker container
DONE

[ /etc/cont-init.d/90-configure_neko.sh: executing... ]
**** Configure Neko ****
  - Disable Neko server
DONE

[ /etc/cont-init.d/90-configure_steam.sh: executing... ]
**** Configure Steam ****
  - Enable Steam auto-start script
  - Steam config already exists, skipping initialization
  - Steam library config already exists, skipping initialization
DONE

[ /etc/cont-init.d/90-configure_sunshine.sh: executing... ]
**** Configure Sunshine ****
  - Enable Sunshine server
DONE

[ /etc/cont-init.d/90-configure_vnc.sh: executing... ]
**** Configure VNC ****
  - Configure VNC service port '32036'
  - Configure pulseaudio encoded stream port '32037'
  - Enable VNC server
  - Disable audio stream
  - Disable audio websock
DONE

[ /etc/cont-init.d/95-setup_wol.sh: executing... ]
**** Configure WoL Manager ****
  - Disable WoL Manager service.

**** Starting supervisord ****
  - Logging all root services to '/var/log/supervisor/'
  - Logging all user services to '/home/default/.cache/log/'

2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/dbus.ini" during parsing
2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/desktop.ini" during parsing
2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/neko.ini" during parsing
2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/pulseaudio.ini" during parsing
2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/steam.ini" during parsing
2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/sunshine.ini" during parsing
2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/udev.ini" during parsing
2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/vnc-audio.ini" during parsing
2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/vnc.ini" during parsing
2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/wol-power-manager.ini" during parsing
2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/xorg.ini" during parsing
2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/xvfb.ini" during parsing
2025-11-16 00:49:29,606 INFO Set uid to user 0 succeeded
2025-11-16 00:49:29,608 INFO RPC interface 'supervisor' initialized
2025-11-16 00:49:29,608 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2025-11-16 00:49:29,608 INFO supervisord started with pid 1563
2025-11-16 00:49:30,611 INFO spawned: 'dbus' with pid 1832
2025-11-16 00:49:30,613 INFO spawned: 'udev' with pid 1833
2025-11-16 00:49:30,615 INFO spawned: 'xorg' with pid 1834
2025-11-16 00:49:30,617 INFO spawned: 'frontend' with pid 1835
2025-11-16 00:49:30,619 INFO spawned: 'pulseaudio' with pid 1836
2025-11-16 00:49:30,621 INFO spawned: 'x11vnc' with pid 1838
2025-11-16 00:49:30,622 INFO spawned: 'desktop' with pid 1839
2025-11-16 00:49:30,623 INFO spawned: 'sunshine' with pid 1842
PULSEAUDIO: Starting pulseaudio service
2025-11-16 00:49:30,675 WARN exited: xorg (exit status 1; not expected)
2025-11-16 00:49:31,663 INFO success: dbus entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-11-16 00:49:31,663 INFO success: udev entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-11-16 00:49:31,663 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-11-16 00:49:31,663 INFO success: pulseaudio entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-11-16 00:49:31,663 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-11-16 00:49:31,663 INFO success: desktop entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-11-16 00:49:31,663 INFO success: sunshine entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-11-16 00:49:31,740 INFO spawned: 'xorg' with pid 1900
2025-11-16 00:49:31,793 WARN exited: xorg (exit status 1; not expected)
2025-11-16 00:49:34,678 INFO spawned: 'xorg' with pid 1940
2025-11-16 00:49:34,743 WARN exited: xorg (exit status 1; not expected)
2025-11-16 00:49:38,669 INFO spawned: 'xorg' with pid 1990
2025-11-16 00:49:38,730 WARN exited: xorg (exit status 1; not expected)
2025-11-16 00:49:39,731 INFO gave up: xorg entered FATAL state, too many start retries too quickly
```

```bash
# .cache/log/sunshine.log
FATAL: /usr/bin/start-sunshine.sh: Gave up waiting for X server :55
# .cache/log/desktop.log
FATAL: /usr/bin/start-desktop.sh: Gave up waiting for X server :55
```
So i assume Xorg problems. 

```bash
# xorg.err.log
(II) Module glxserver_nvidia: vendor="NVIDIA Corporation"
	compiled for 1.6.99.901, module version = 1.0.0
(II) NVIDIA GLX Module  580.105.08  Wed Oct 29 22:17:01 UTC 2025
(II) NVIDIA: The X server supports PRIME Render Offload.
(--) NVIDIA(0): Valid display device(s) on GPU-0 at PCI:41:0:0
(--) NVIDIA(0):     DFP-0
(--) NVIDIA(0):     DFP-1
(--) NVIDIA(0):     DFP-2
(--) NVIDIA(0):     DFP-3
(--) NVIDIA(0):     DFP-4
(--) NVIDIA(0):     DFP-5 (boot)
(--) NVIDIA(0):     DFP-6
(**) NVIDIA(0): Using ConnectedMonitor string "DFP-0".
(II) NVIDIA(0): NVIDIA GPU NVIDIA GeForce RTX 4090 (AD102-A) at PCI:41:0:0
(II) NVIDIA(0):     (GPU-0)
(--) NVIDIA(0): Memory: 25153536 kBytes
(--) NVIDIA(0): VideoBIOS: 95.02.3c.00.fc
(II) NVIDIA(0): Detected PCI Express Link width: 16X
(EE) NVIDIA(GPU-0): Failed to acquire modesetting permission.
(EE) NVIDIA(0): Failing initialization of X screen
(II) Unloading glxserver_nvidia
(EE) Screen(s) found, but none have a usable configuration.
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.55.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
```

**Comment by zer0ish** [comment]
> I encountered the same issue, but in Ubuntu 20.04 , (Fresh installed OS, clean)
> 
> * CPU: Ryzen9 3950X (no iGPU)
> * GPU: MSI RTX 4090
> * OS:  Ubuntu 20.04.6 LTS
> * Kernel: 5.15.0-139-generic
> * Docker: Docker version 28.1.1, build 4eba377
> * Host driver: 580.105.08
> 
> `docker-compose.yml` is the same **zer0ish** provided above, just changed the volume path for log & game folder.
> 
> ## situation:
> Able to connect `http://<ip>:8086`, showing the VNC page , `Failed to connect to server` banner pops out when clicking `Connect` button.
> 
> ## attempted:
> * [x]  (host) blacklist noveau (`blacklist nouveau` & `options nouveau modeset=0`)[x]  (host) setting drm (`options nvidia-drm modeset=1`)[x]  tried `DISPLAY=:55`[x]  (container)tried different nvidia driver  `580.105.08(cuda13.0)` & `570.124.04(cuda12.8)`[x]  (debugging) trying to forward X11 to host `DISPLAY=:0` , `DISPLAY=unix:0` , checking Xorg or gpu driver problem
> 
> ## Log:
> [ /etc/cont-init.d/10-setup_user.sh: executing... ]
> **** Configure default user ****
>   - Setting default user uid=99(default) gid=100(default)
> usermod: no changes
>   - Adding default user to any additional required device groups
>   - Adding user 'default' to group: 'video'
>   - Adding user 'default' to group: 'audio'
>   - Adding user 'default' to group: 'input'
>   - Adding user 'default' to group: 'pulse'
>   - Adding user 'default' to group: 'avahi' for device: /dev/input/event0
>   - Setting umask to 000
>   - Create the user XDG_RUNTIME_DIR path '/tmp/.X11-unix/run'
>   - Setting ownership of all log files in '/home/default/.cache/log'
>   - Setting root password
>   - Setting user password
> DONE
> 
> [ /etc/cont-init.d/11-setup_sysctl_values.sh: executing... ]
> **** Configure some system kernel parameters ****
>   - The vm.max_map_count is already greater than '524288'
> DONE
> 
> [ /etc/cont-init.d/30-configure_dbus.sh: executing... ]
> **** Configure container dbus ****
>   - Container configured to run its own dbus
> DONE
> 
> [ /etc/cont-init.d/30-configure_udev.sh: executing... ]
> **** Configure udevd ****
>   - Configure container to run udev management
>   - Ensure the default user has permission to r/w on input devices
> DONE
> 
> [ /etc/cont-init.d/40-setup_locale.sh: executing... ]
> **** Configure local ****
>   - Locales already set correctly to en_US.UTF-8 UTF-8
> DONE
> 
> [ /etc/cont-init.d/50-configure_pulseaudio.sh: executing... ]
> **** Configure pulseaudio ****
>   - Enable pulseaudio service.
>   - Configure pulseaudio to pipe audio to a socket
> DONE
> 
> [ /etc/cont-init.d/60-configure_gpu_driver.sh: executing... ]
> **** No Intel device found ****
> **** No AMD device found ****
> **** Found NVIDIA device 'NVIDIA GeForce RTX 4090' ****
>   - NVIDIA driver version 580.105.08 is already installed
>   - Leaving NVIDIA driver stock without patching
> DONE
> 
> [ /etc/cont-init.d/70-configure_desktop.sh: executing... ]
> **** Configure Desktop ****
>   - Enable Desktop service.
> DONE
> 
> [ /etc/cont-init.d/70-configure_xorg.sh: executing... ]
> **** Generate NVIDIA xorg.conf ****
>   - Configure container as primary the X server
>   - Enabling evdev input class on pointers, keyboards, touchpads, touch screens, etc.
>   - Configuring X11 with GPU ID: 'GPU-7e6f4521-b3fc-657c-0366-4c4c2a3c0299'
>   - Configuring X11 with PCI bus ID: 'PCI:41:0:0'
>   - Writing X11 config with Modeline "1600x900R"  201.00  1600 1648 1680 1760  900 903 908 953 +hsync -vsync
> 
> WARNING: Unable to locate/open X configuration file.
> 
> Option "ProbeAllGpus" "False" added to Screen "Screen0".
> Option "BaseMosaic" "False" added to Screen "Screen0".
> Option "AllowEmptyInitialConfiguration" "True" added to Screen "Screen0".
> New X configuration file written to '/etc/X11/xorg.conf'
> 
> DONE
> 
> [ /etc/cont-init.d/80-configure_flatpak.sh: executing... ]
> **** Configure Flatpak ****
>   - Flatpak configured for running inside a Docker container
> DONE
> 
> [ /etc/cont-init.d/90-configure_neko.sh: executing... ]
> **** Configure Neko ****
>   - Disable Neko server
> DONE
> 
> [ /etc/cont-init.d/90-configure_steam.sh: executing... ]
> **** Configure Steam ****
>   - Enable Steam auto-start script
>   - Steam config already exists, skipping initialization
>   - Steam library config already exists, skipping initialization
> DONE
> 
> [ /etc/cont-init.d/90-configure_sunshine.sh: executing... ]
> **** Configure Sunshine ****
>   - Enable Sunshine server
> DONE
> 
> [ /etc/cont-init.d/90-configure_vnc.sh: executing... ]
> **** Configure VNC ****
>   - Configure VNC service port '32036'
>   - Configure pulseaudio encoded stream port '32037'
>   - Enable VNC server
>   - Disable audio stream
>   - Disable audio websock
> DONE
> 
> [ /etc/cont-init.d/95-setup_wol.sh: executing... ]
> **** Configure WoL Manager ****
>   - Disable WoL Manager service.
> 
> **** Starting supervisord ****
>   - Logging all root services to '/var/log/supervisor/'
>   - Logging all user services to '/home/default/.cache/log/'
> 
> 2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/dbus.ini" during parsing
> 2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/desktop.ini" during parsing
> 2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/neko.ini" during parsing
> 2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/pulseaudio.ini" during parsing
> 2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/steam.ini" during parsing
> 2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/sunshine.ini" during parsing
> 2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/udev.ini" during parsing
> 2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/vnc-audio.ini" during parsing
> 2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/vnc.ini" during parsing
> 2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/wol-power-manager.ini" during parsing
> 2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/xorg.ini" during parsing
> 2025-11-16 00:49:29,606 INFO Included extra file "/etc/supervisor.d/xvfb.ini" during parsing
> 2025-11-16 00:49:29,606 INFO Set uid to user 0 succeeded
> 2025-11-16 00:49:29,608 INFO RPC interface 'supervisor' initialized
> 2025-11-16 00:49:29,608 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> 2025-11-16 00:49:29,608 INFO supervisord started with pid 1563
> 2025-11-16 00:49:30,611 INFO spawned: 'dbus' with pid 1832
> 2025-11-16 00:49:30,613 INFO spawned: 'udev' with pid 1833
> 2025-11-16 00:49:30,615 INFO spawned: 'xorg' with pid 1834
> 2025-11-16 00:49:30,617 INFO spawned: 'frontend' with pid 1835
> 2025-11-16 00:49:30,619 INFO spawned: 'pulseaudio' with pid 1836
> 2025-11-16 00:49:30,621 INFO spawned: 'x11vnc' with pid 1838
> 2025-11-16 00:49:30,622 INFO spawned: 'desktop' with pid 1839
> 2025-11-16 00:49:30,623 INFO spawned: 'sunshine' with pid 1842
> PULSEAUDIO: Starting pulseaudio service
> 2025-11-16 00:49:30,675 WARN exited: xorg (exit status 1; not expected)
> 2025-11-16 00:49:31,663 INFO success: dbus entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2025-11-16 00:49:31,663 INFO success: udev entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2025-11-16 00:49:31,663 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2025-11-16 00:49:31,663 INFO success: pulseaudio entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2025-11-16 00:49:31,663 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2025-11-16 00:49:31,663 INFO success: desktop entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2025-11-16 00:49:31,663 INFO success: sunshine entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2025-11-16 00:49:31,740 INFO spawned: 'xorg' with pid 1900
> 2025-11-16 00:49:31,793 WARN exited: xorg (exit status 1; not expected)
> 2025-11-16 00:49:34,678 INFO spawned: 'xorg' with pid 1940
> 2025-11-16 00:49:34,743 WARN exited: xorg (exit status 1; not expected)
> 2025-11-16 00:49:38,669 INFO spawned: 'xorg' with pid 1990
> 2025-11-16 00:49:38,730 WARN exited: xorg (exit status 1; not expected)
> 2025-11-16 00:49:39,731 INFO gave up: xorg entered FATAL state, too many start retries too quickly
> # .cache/log/sunshine.log
> FATAL: /usr/bin/start-sunshine.sh: Gave up waiting for X server :55
> # .cache/log/desktop.log
> FATAL: /usr/bin/start-desktop.sh: Gave up waiting for X server :55
> So i assume Xorg problems.
> 
> # xorg.err.log
> (II) Module glxserver_nvidia: vendor="NVIDIA Corporation"
> 	compiled for 1.6.99.901, module version = 1.0.0
> (II) NVIDIA GLX Module  580.105.08  Wed Oct 29 22:17:01 UTC 2025
> (II) NVIDIA: The X server supports PRIME Render Offload.
> (--) NVIDIA(0): Valid display device(s) on GPU-0 at PCI:41:0:0
> (--) NVIDIA(0):     DFP-0
> (--) NVIDIA(0):     DFP-1
> (--) NVIDIA(0):     DFP-2
> (--) NVIDIA(0):     DFP-3
> (--) NVIDIA(0):     DFP-4
> (--) NVIDIA(0):     DFP-5 (boot)
> (--) NVIDIA(0):     DFP-6
> (**) NVIDIA(0): Using ConnectedMonitor string "DFP-0".
> (II) NVIDIA(0): NVIDIA GPU NVIDIA GeForce RTX 4090 (AD102-A) at PCI:41:0:0
> (II) NVIDIA(0):     (GPU-0)
> (--) NVIDIA(0): Memory: 25153536 kBytes
> (--) NVIDIA(0): VideoBIOS: 95.02.3c.00.fc
> (II) NVIDIA(0): Detected PCI Express Link width: 16X
> (EE) NVIDIA(GPU-0): Failed to acquire modesetting permission.
> (EE) NVIDIA(0): Failing initialization of X screen
> (II) Unloading glxserver_nvidia
> (EE) Screen(s) found, but none have a usable configuration.
> (EE) 
> Fatal server error:
> (EE) no screens found(EE) 
> (EE) 
> Please consult the The X.Org Foundation support 
> 	 at http://wiki.x.org
>  for help. 
> (EE) Please also check the log file at "/var/log/Xorg.55.log" for additional information.
> (EE) 
> (EE) Server terminated with error (1). Closing log file.

Sorry, I tried to get an ubuntu VM going, but don't have a spare gpu to throw at it to try and test.
Usually when you can get to the VNC browser window but can't connect to Steam after from VNC, it's usually a user permissions problem.
I see from the log, you are using "default" as the user.
  - Adding user 'default' to group: 'video'
  - Adding user 'default' to group: 'audio'
  - Adding user 'default' to group: 'input'
  - Adding user 'default' to group: 'pulse'
  - Adding user 'default' to group: 'avahi' for device: /dev/input/event0


This is what I have to use for my unraid server, since 99/100 is the nobody user PUID/PGID that docker uses. In TrueNAS it's 568/568 for PUID/PGID. Without seeing the exact yaml you used I don't know what user PUID/PGID you used but looks like it's "default". You might have to go look at the Shadow file and see what your docker user PUID/PGID are and use those.
 - PUID=99  # 99 for unraid / or what ever user for the OS you're using
 - PGID=100  # 100 for unraid / or what ever user for the OS you're using

I'm not a wizard in Linux, but based on past experience it seems like a PUID/PGID issue if you used my docker-compose yaml.
I should be getting one of my spare laptops back from a friend at somepoint and can test again with that.

**Comment by royinx** [comment]
Solved, thanks zer0ish for the new docker-compose file. 

I am using Ubuntu Desktop, which already running one X server (Xorg) for GUI.  
According to [Post](https://forums.developer.nvidia.com/t/nvidia-gpu-0-failed-to-acquire-modesetting-permission/213267/2), only one X server actively using one nvidia gpu, means need to suspend first X server to start a second X server. 

here is the command to disable / suspend the Xorg, then the resource will be free, then container may able to access. 

### Turn off Host OS Xorg
```bash
sudo systemctl stop display-manager
nvidia-smi # process 'Xorg' will disappear
sudo systemctl disable gdm.service # Optional - disable auto start gdm when login

docker compose up --force-recreate
```

### How to restore GUI
```
sudo dpkg-reconfigure gdm3
sudo systemctl start display-manager
```

---

My issue is from GUI (Xorg occupancy),  not sure will this help no GUI OS in NAS / server / headless. 
If you have iGPU in your CPU ,  I guess you can switch to iGPU in BIOS for Host OS GUI .
you can also use Wayland instead of Xorg for Host OS GUI

---

For reference, my updated docker-compose.yaml :
```
---
services:
  steam-headless_new:  # change the name to what you want
    # build: Dockerfile.debian
    image: josh5/steam-headless:latest
    restart: unless-stopped
    privileged: true
    runtime: nvidia
    container_name: Steam-Headless_NEW  # change the name to what you want
    shm_size: 6G
    ipc: host # Could also be set to 'shareable'
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    
    # NETWORK:
    ## NOTE:  With this configuration, if we do not use the host network, then physical device input
    ##        is not possible and your USB connesuncted controllers will not work in steam games.
    network_mode: host
    hostname: Steam-Headless_NEW  # change the name to what you want
    extra_hosts:
      - "Steam-Headless_NEW:127.0.0.1" # change the name to match container/hostname

    # ENVIRONMENT:
    ## Read all config variables from the .env file
    environment:
      # System
      - TZ=America/Toronto
      - USER_LOCALES=en_US.UTF-8 UTF-8
      - DISPLAY=:55
      # User
      - PUID=1000  # 99 for unraid / or what ever user for the OS you're using
      - PGID=1000  # 100 for unraid / or what ever user for the OS you're using
      - UMASK=000
      - USER_PASSWORD=password   #what ever password you want to use, not sure what it's used for
      # Mode
      - MODE=primary
      # Web UI
      - WEB_UI_MODE=vnc
      - ENABLE_VNC_AUDIO=false
      - PORT_NOVNC_WEB=8086
      # Xorg
      - ENABLE_EVDEV_INPUTS=true
      - FORCE_X11_DUMMY_CONFIG=true
      # Nvidia specific config
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all   #or what ever GPU ID you want to use
      - NVIDIA_DRIVER_VERSION=  # I left this blank to use what was the base server drivers.
      # auto startup
      - ENABLE_STEAM=true
      - ENABLE_SUNSHINE=true
    # VOLUMES:
    volumes:
      - /CHANGE/TO/YOUR/PATH/:/home/default
      - /CHANGE/TO/YOUR/PATH/:/mnt/games/
     
      - /tmp/.X11-unix/:/tmp/.X11-unix/:r/w
      - /tmp/tmp/pulse/:/tmp/pulse/:r/w
      - /dev/input/:/dev/input/:r/w
    # devices:
    #   - /dev/dri/:/dev/dri/:r/w
    #   - /dev/uhid/:/dev/uhid/:r/w
```

Edit (2025-12-14) 
I found that `ipc=host` might cause no sound , a conflict between container's pulseaudio  & host's pulseaudio.
which may not be found by moonlight , so I'm using steam link to play. 
if someone figure out how to use sunshine , please let me know!

**Comment by Ryaang** [comment]
> My issue is from GUI (Xorg occupancy), not sure will this help no GUI OS in NAS / server / headless. If you have iGPU in your CPU , I guess you can switch to iGPU in BIOS for Host OS GUI . you can also use Wayland instead of Xorg for Host OS GUI

thank you a lot, my problem is solved by this!

**Comment by Archmonger** [comment]
As suggested above, **Unraid GUI boot must be disabled** when using the latest Unraid Docker with the `--runtime='nvidia'` flag.

The instructions in the docker template did not work to re-use the Unraid host X11 server. It was generating logs that showed `polkit` was infinitely failing to start up. Setting the docker to privileged did not fix it. Perhaps `Mode: 'secondary'` might be making some unsafe assumptions on Unraid 7?

**Comment by ameoverflow** [comment]
> Solved, thanks zer0ish for the new docker-compose file.
> 
> I am using Ubuntu Desktop, which already running one X server (Xorg) for GUI. According to [Post](https://forums.developer.nvidia.com/t/nvidia-gpu-0-failed-to-acquire-modesetting-permission/213267/2), only one X server actively using one nvidia gpu, means need to suspend first X server to start a second X server.
> 
> here is the command to disable / suspend the Xorg, then the resource will be free, then container may able to access.
> ### Turn off Host OS Xorg
> 
> sudo systemctl stop display-manager
> nvidia-smi # process 'Xorg' will disappear
> sudo systemctl disable gdm.service # Optional - disable auto start gdm when login
> 
> docker compose up --force-recreate
> 
> ### How to restore GUI
> 
> ```
> sudo dpkg-reconfigure gdm3
> sudo systemctl start display-manager
> ```
> 
> My issue is from GUI (Xorg occupancy), not sure will this help no GUI OS in NAS / server / headless. If you have iGPU in your CPU , I guess you can switch to iGPU in BIOS for Host OS GUI . you can also use Wayland instead of Xorg for Host OS GUI
> 
> For reference, my updated docker-compose.yaml :
> 
> ```
> ---
> services:
>   steam-headless_new:  # change the name to what you want
>     # build: Dockerfile.debian
>     image: josh5/steam-headless:latest
>     restart: unless-stopped
>     privileged: true
>     runtime: nvidia
>     container_name: Steam-Headless_NEW  # change the name to what you want
>     shm_size: 6G
>     ipc: host # Could also be set to 'shareable'
>     ulimits:
>       nofile:
>         soft: 1024
>         hard: 524288
>     
>     # NETWORK:
>     ## NOTE:  With this configuration, if we do not use the host network, then physical device input
>     ##        is not possible and your USB connesuncted controllers will not work in steam games.
>     network_mode: host
>     hostname: Steam-Headless_NEW  # change the name to what you want
>     extra_hosts:
>       - "Steam-Headless_NEW:127.0.0.1" # change the name to match container/hostname
> 
>     # ENVIRONMENT:
>     ## Read all config variables from the .env file
>     environment:
>       # System
>       - TZ=America/Toronto
>       - USER_LOCALES=en_US.UTF-8 UTF-8
>       - DISPLAY=:55
>       # User
>       - PUID=1000  # 99 for unraid / or what ever user for the OS you're using
>       - PGID=1000  # 100 for unraid / or what ever user for the OS you're using
>       - UMASK=000
>       - USER_PASSWORD=password   #what ever password you want to use, not sure what it's used for
>       # Mode
>       - MODE=primary
>       # Web UI
>       - WEB_UI_MODE=vnc
>       - ENABLE_VNC_AUDIO=false
>       - PORT_NOVNC_WEB=8086
>       # Xorg
>       - ENABLE_EVDEV_INPUTS=true
>       - FORCE_X11_DUMMY_CONFIG=true
>       # Nvidia specific config
>       - NVIDIA_DRIVER_CAPABILITIES=all
>       - NVIDIA_VISIBLE_DEVICES=all   #or what ever GPU ID you want to use
>       - NVIDIA_DRIVER_VERSION=  # I left this blank to use what was the base server drivers.
>       # auto startup
>       - ENABLE_STEAM=true
>       - ENABLE_SUNSHINE=true
>     # VOLUMES:
>     volumes:
>       - /CHANGE/TO/YOUR/PATH/:/home/default
>       - /CHANGE/TO/YOUR/PATH/:/mnt/games/
>      
>       - /tmp/.X11-unix/:/tmp/.X11-unix/:r/w
>       - /tmp/tmp/pulse/:/tmp/pulse/:r/w
>       - /dev/input/:/dev/input/:r/w
>     # devices:
>     #   - /dev/dri/:/dev/dri/:r/w
>     #   - /dev/uhid/:/dev/uhid/:r/w
> ```
> 
> Edit (2025-12-14) I found that `ipc=host` might cause no sound , a conflict between container's pulseaudio & host's pulseaudio. which may not be found by moonlight , so I'm using steam link to play. if someone figure out how to use sunshine , please let me know!

thanks, this basically solves the issue, i have no issues with ipc=host, and i need to stop sddm despite plasma running on wayland, in order for container to start, because sddm itself runs on xorg by default iirc

**Comment by ameoverflow** [comment]
> invalid:pebcak

dunno how is it a pebcak issue if it worked only when i used docker compose.yml written by another user, not the one from documentation

> [...] but you can't use the docker compose template and env options provided. Not sure why that doesn't work.

**Comment by royinx** [comment]
> invalid:pebcak 

Because this repo is so well-built and widely applicable across Linux distros, users on Desktop (non-server) OS naturally assume the container will spawn an isolated virtual GUI (much like Webtop does with Xvfb/Xorg) without conflicting with the host's existing Xorg/Wayland session.

If the documentation could explicitly mention potential resource or device conflicts when running on a Host with an active GUI, it would significantly reduce 'user errors' and help those not running on a headless server. It’s not necessarily a user mistake, but rather a high expectation of the container's isolation capabilities."

---

> but you can't use the docker compose template and env options provided. Not sure why that doesn't work.

## Update permission for `udev` exit problems. 

```diff 
# docker-compose.nvidia.privileged.yml
     volumes:
       ...
+      - /dev/input/:/dev/input/:r/w
-      - /dev/input/:/dev/input/:ro
```


## If above not work, Check GPU Occupying by Host OS 

```bash
sudo systemctl stop display-manager     # try terminate Host GUI
docker restart steam-headless           # restart container
```

if works, issue probably caused by [Xorg](https://github.com/Steam-Headless/docker-steam-headless/issues/200#issuecomment-3540172221).

**Comment by Josh5** [comment]
Im open to PRs. Would probably take just a few mins to submit a docs update or a new compose template that works for your situation. Otherwise, if no one wants to submit a PR, this issue will eventually be closed as PEBKAC with nothing done.

This is a configuration issue, not something I need to fix about the container or in any code. Hence, this label. My time is limited, and this is not something I can verify myself, so Im not going to be the one to create any documentation around it.

**Comment by royinx** [comment]
thanks Josh, I submitted a PR for above issue.

I also run some further test across different OS and mark a note share here.  
Assuming server OS has no desktop UI by default, I just tested on desktop OS: 
ubuntu 20.04 (Xorg) , ubuntu 22.04 (wayland) and arch (wayland).

Basically most desktop operating systems will encounter GPU resource conflicts due to the DRM (Direct Rendering Manager)architecture.  Under this design, the DRM Master acts as a mutual exclusion lock; only the process holding this 'Master' status has the authority to control the Display Engine. 
Note that the DRM follows a 'first-come, first-served' principle. Both Wayland compositor / X11 window manager will still occupy DRM master lock. 

And there are a very interesting result that ubuntu 2204 has no conflict will DRM, but will overlay with Host Desktop UI. 

<img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/bd1e5575-97fd-4be0-988f-10cdabab0f6e" />


  | Display | Require to suspend Host Display | Container GUI Rendered to Host UI
-- | -- | -- | --
ubuntu 20.04 | Xorg | Yes❌ | No
ubuntu 22.04 | Xwayland | No ✅ | Yes **(Virtual Desktop will render and merge with existing Host Desktop)
Arch(Wayland, GNOME) | Xwayland(Tested on mutter / Cosmic / plasma) | Yes❌ | Yes(Virtual Desktop will show on monitor)


---

For those who want concurrent Host and Remote usage, `vgpu_unlock` is a viable path to partition consumer GPUs and overcome DRM constraints.  However, as this significantly increases setup complexity and will deviates from the convenience of this repo.

**Comment by ameoverflow** [comment]
>   	Display 	Require to suspend Host Display 	Container GUI Rendered to Host UI
> ubuntu 20.04 	Xorg 	Yes❌ 	No
> ubuntu 22.04 	Xwayland 	No ✅ 	Yes **(Virtual Desktop will render and merge with existing Host Desktop)
> Arch(Wayland, GNOME) 	Xwayland(Tested on mutter / Cosmic / plasma) 	Yes❌ 	Yes(Virtual Desktop will show on monitor)
> 
> For those who want concurrent Host and Remote usage, `vgpu_unlock` is a viable path to partition consumer GPUs and overcome DRM constraints. However, as this significantly increases setup complexity and will deviates from the convenience of this repo.

On Arch my display was just blank after doing `systemctl stop sddm`, `systemctl stop display-manager` and then starting the container (SDDM set to use Wayland).

**Comment by nekename** [comment]
> I found that Xorg is working correctly using the bridge network mode, but I did not see the same ports as the host.

This is what worked for me: changing `network_mode: host` to `network_mode: bridge` in compose.yaml. This happened on my system with an Arc A380 and peripherals connected with a real (Wayland) desktop installed and running, but not on my actually headless system. 

Edit: I did, of course, have to add
```
ports:
  - ${PORT_NOVNC_WEB}:${PORT_NOVNC_WEB}
```
to the compose file as well, and then have to run into #218 and use the workaround mentioned there

**Comment by msuadOf** [comment]
Do you know any reason for my log output? I am doubting my driver version(it is 550.120) is the reason, but as you know, change nvidia driver version may cause kernel unmatched, I trying to not use driver above 570.
```
steam-headless-1  | 2026-03-30 01:25:46,584 INFO Included extra file "/etc/supervisor.d/accounts-daemon.ini" during parsing
steam-headless-1  | 2026-03-30 01:25:46,584 INFO Included extra file "/etc/supervisor.d/dbus.ini" during parsing
steam-headless-1  | 2026-03-30 01:25:46,584 INFO Included extra file "/etc/supervisor.d/desktop.ini" during parsing
steam-headless-1  | 2026-03-30 01:25:46,584 INFO Included extra file "/etc/supervisor.d/neko.ini" during parsing
steam-headless-1  | 2026-03-30 01:25:46,584 INFO Included extra file "/etc/supervisor.d/polkit.ini" during parsing
steam-headless-1  | 2026-03-30 01:25:46,584 INFO Included extra file "/etc/supervisor.d/pulseaudio.ini" during parsing
steam-headless-1  | 2026-03-30 01:25:46,584 INFO Included extra file "/etc/supervisor.d/steam.ini" during parsing
steam-headless-1  | 2026-03-30 01:25:46,584 INFO Included extra file "/etc/supervisor.d/sunshine.ini" during parsing
steam-headless-1  | 2026-03-30 01:25:46,584 INFO Included extra file "/etc/supervisor.d/udev.ini" during parsing
steam-headless-1  | 2026-03-30 01:25:46,584 INFO Included extra file "/etc/supervisor.d/vnc-audio.ini" during parsing
steam-headless-1  | 2026-03-30 01:25:46,584 INFO Included extra file "/etc/supervisor.d/vnc.ini" during parsing
steam-headless-1  | 2026-03-30 01:25:46,584 INFO Included extra file "/etc/supervisor.d/wol-power-manager.ini" during parsing
steam-headless-1  | 2026-03-30 01:25:46,584 INFO Included extra file "/etc/supervisor.d/xorg.ini" during parsing
steam-headless-1  | 2026-03-30 01:25:46,584 INFO Included extra file "/etc/supervisor.d/xvfb.ini" during parsing
steam-headless-1  | 2026-03-30 01:25:46,584 INFO Set uid to user 0 succeeded
steam-headless-1  | 2026-03-30 01:25:46,590 INFO RPC interface 'supervisor' initialized
steam-headless-1  | 2026-03-30 01:25:46,590 CRIT Server 'unix_http_server' running without any HTTP authentication checking
steam-headless-1  | 2026-03-30 01:25:46,590 INFO supervisord started with pid 1
steam-headless-1  | 2026-03-30 01:25:47,595 INFO spawned: 'dbus' with pid 502
steam-headless-1  | 2026-03-30 01:25:47,599 INFO spawned: 'udev' with pid 503
steam-headless-1  | 2026-03-30 01:25:47,603 INFO spawned: 'polkit' with pid 504
steam-headless-1  | 2026-03-30 01:25:47,606 INFO spawned: 'accounts-daemon' with pid 505
steam-headless-1  | 2026-03-30 01:25:47,609 INFO spawned: 'xorg' with pid 506
steam-headless-1  | 2026-03-30 01:25:47,613 INFO spawned: 'audiostream' with pid 508
steam-headless-1  | 2026-03-30 01:25:47,616 INFO spawned: 'frontend' with pid 509
steam-headless-1  | 2026-03-30 01:25:47,619 INFO spawned: 'pulseaudio' with pid 510
steam-headless-1  | 2026-03-30 01:25:47,621 INFO spawned: 'x11vnc' with pid 512
steam-headless-1  | 2026-03-30 01:25:47,624 INFO spawned: 'desktop' with pid 520
steam-headless-1  | PULSEAUDIO: Starting pulseaudio service
steam-headless-1  | 2026-03-30 01:25:47,668 INFO reaped unknown pid 544 (exit status 0)
steam-headless-1  | 2026-03-30 01:25:48,646 INFO success: dbus entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2026-03-30 01:25:48,646 INFO success: udev entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2026-03-30 01:25:48,646 INFO success: polkit entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2026-03-30 01:25:48,646 INFO success: accounts-daemon entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2026-03-30 01:25:48,646 INFO success: xorg entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2026-03-30 01:25:48,646 INFO success: audiostream entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2026-03-30 01:25:48,646 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2026-03-30 01:25:48,646 INFO success: pulseaudio entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2026-03-30 01:25:48,646 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2026-03-30 01:25:48,647 INFO success: desktop entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
steam-headless-1  | 2026-03-30 01:25:48,723 WARN exited: xorg (exit status 1; not expected)
steam-headless-1  | 2026-03-30 01:25:48,907 INFO spawned: 'xorg' with pid 577
steam-headless-1  | 2026-03-30 01:25:49,018 WARN exited: xorg (exit status 1; not expected)
steam-headless-1  | 2026-03-30 01:25:50,926 INFO spawned: 'xorg' with pid 604
steam-headless-1  | 2026-03-30 01:25:51,032 WARN exited: xorg (exit status 1; not expected)
steam-headless-1  | 2026-03-30 01:25:53,802 INFO spawned: 'xorg' with pid 630
steam-headless-1  | 2026-03-30 01:25:53,906 WARN exited: xorg (exit status 1; not expected)
steam-headless-1  | 2026-03-30 01:25:57,316 INFO spawned: 'xorg' with pid 675
steam-headless-1  | 2026-03-30 01:25:57,424 WARN exited: xorg (exit status 1; not expected)
steam-headless-1  | 2026-03-30 01:25:58,425 INFO gave up: xorg entered FATAL state, too many start retries too quickly
```

**Comment by royinx** [comment]
@msuadOf would you mind to open a new issue, it's hard to tell without any background to reproduce.

@ameoverflow Thanks for raising the issue, Josh has merged the PR, you may close the issue . 
If there are follow-up issues , please re-open this post anytime.
